name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
  deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: EmbarkStudios/cargo-deny-action@v1
  vhs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # We need to build it, otherwise the `cargo run` will take way too long,
      # breaking the vhs script
      # TODO: Move this to the build job if we need to build it anyway?
      - name: Build
        run: cargo build --verbose
      - uses: charmbracelet/vhs-action@v1
        with:
          path: misc/demo.tape
      - run: git diff --exit-code misc/demo.ascii
